export const UI_TEXT = {
    en: {
        appTitle: "Outly",
        dashboardTitle: "DASHBOARD",
        weatherChatTitle: "CHAT",
        chatBotTitle: "Chat Bot",
        tagline: "Your Weather & Activity Companion",
        cityLabel: "City",
        cityPlaceholder: "Enter city name...",
        useMyLocation: "Use My Location",
        dateTimeLabel: "Date & Time",
        currentWeather: "Current Weather",
        startChat: "Start Chat with Outly",
        selectLocationError: "Please select a location first",
        backToDashboard: "Back to Dashboard",
        switchToLight: "Switch to Light Mode",
        switchToDark: "Switch to Dark Mode",
        languageMeta: "EN",
        activitiesTitle: "Best Activities Today",
        learnMore: "Learn More",
        forecastTitle: "5-Day Forecast",
        weatherSummaryTitle: "Weather Summary",
        clearChat: "Clear Chat",
        clearChatTooltip: "Clear chat history",
        emptyChatTitle: "How can I help you today?",
        emptyChatDesc: "I can help you plan your hike, bike ride, or outfit based on the weather. Ask me anything!",
        chatPlaceholder: "Type your message...",
        voiceInput: "Voice input",
        sendButton: "Send",
        wind: "Wind",
        humidity: "Humidity",
        feelsLike: "Feels Like",
        visibility: "Visibility"
    },
    ja: {
        appTitle: "Outly",
        dashboardTitle: "ダッシュボード",
        weatherChatTitle: "チャット",
        chatBotTitle: "チャットボット",
        tagline: "あなたの天気とアクティビティのパートナー",
        cityLabel: "都市",
        cityPlaceholder: "都市名を入力...",
        useMyLocation: "現在地を使用",
        dateTimeLabel: "日時",
        currentWeather: "現在の天気",
        startChat: "Outlyとチャットを開始",
        selectLocationError: "まず場所を選択してください",
        backToDashboard: "ダッシュボードに戻る",
        switchToLight: "ライトモードに切り替え",
        switchToDark: "ダークモードに切り替え",
        languageMeta: "JP",
        activitiesTitle: "今日のおすすめアクティビティ",
        learnMore: "詳細を見る",
        forecastTitle: "5日間の予報",
        weatherSummaryTitle: "天気概要",
        clearChat: "チャットをクリア",
        clearChatTooltip: "チャット履歴をクリア",
        emptyChatTitle: "今日はどのようにお手伝いしましょうか？",
        emptyChatDesc: "・天気に基づいた服装のアドバイス\n・ハイキングやサイクリングの計画\n何でも聞いてください！",
        chatPlaceholder: "メッセージを入力...",
        voiceInput: "音声入力",
        sendButton: "送信",
        wind: "風",
        humidity: "湿度",
        feelsLike: "体感温度",
        visibility: "視界"
    }
};
